server:
  port: 8156

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
      
spring:
  application:
    name: keycloack
keycloak:
  authorization-uri: ${keycloak.base-uri}Interbank/protocol/openid-connect/auth
  base-uri: http://localhost:9090/realms/
  user-info-uri: ${keycloak.base-uri}Interbank/protocol/openid-connect/userinfo
  token-uri: ${keycloak.base-uri}Interbank/protocol/openid-connect/token
  logout: ${keycloak.base-uri}Interbank/protocol/openid-connect/logout
  jwk-set-uri: ${keycloak.base-uri}Interbank/protocol/openid-connect/certs
  certs-id: 3Rx1f2dSP-MR1Wg1TFGTTJpFb9OFgyzQEMnUe302ep0
  client-id: backend-for-frontend-interbank-app
  client-secret: interbank
  scope: profile
  authorization-grant-type: password
  authorization-grant-type-refresh: refresh_token