server:
  port: 8083
spring:
  application:
    name: business-financial-collection-v1
  data:
    mongodb:
      uri: mongodb://localhost:27017/financial
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
aes:
  secret: interbankpe62024